#pragma once

enum class EProperties {

    // Lilac
    BOUL_BELLEVILLE,
    RUE_LECOURBE,
    RUE_FAUBOURG_SAINT_ANTOINE,
    QUAIS_SEINE,
    MONTMARTRE,

    // Stations
    GARE_MONTPARNASSE,
    GARE_DU_NORD,
    GARE_DE_LYON,
    GARE_SAINT_LAZARE,

    // Light Blue
    RUE_VAUGIRARD,
    RUE_COURCELLES,
    AVENUE_REPUBLIQUE,
    BOUL_CHAPELLE,
    FILLES_CALVAIRE,
    PORTE_LILAS,
    NOTRE_DAME_CHAMPS,

    // Purple
    BOUL_VILLETTE,
    AVENUE_NEUILLY,
    RUE_PARADIS,
    AVENUE_GENERAL_LECLERC,
    RUE_BERCY,
    PONT_ALEXANDRE_III,
    PONT_NEUF,
    PASSERELLE_ARTS,

    // Orange Brown
    AVENUE_MOZART,
    BOUL_SAINT_MICHEL,
    PLACE_PIGALLE,
    AVENUE_CHOISY,
    MUSEE_ORSAY,
    BEAUBOURG,
    CITE_SCIENCES,

    // Red
    AVENUE_MATIGNON,
    BOUL_MALESHERBES,
    AVENUE_HENRI_MARTIN,
    BOUL_HAUSSMANN,
    STADE_FRANCE,
    OLYMPIA,
    PALAIS_OMNISPORTS_BERCY,

    // Yellow
    FAUBOURG_SAINT_HONORE,
    PLACE_BOURSE,
    RUE_LAFAYETTE,
    LYCEE_HENRI_IV,
    ECOLE_ARTS_METIERS,
    SORBONNE,

    // Green
    AVENUE_BRETEUIL,
    AVENUE_FOCH,
    BOUL_CAPUCINES,
    AVENUE_MONTAIGNE,
    AVENUE_GEORGE_V,
    RUE_FRANCOIS_I,
    LA_DEFENSE,
    LA_BOURSE,
    MINISTERE_FINANCES,

    // Dark Blue
    CHAMPS_ELYSEES,
    RUE_PAIX,
    NOTRE_DAME_PARIS,
    TOUR_EIFFEL
};